/* Source-linked, text-rebuilt questions. v=0 is the source redo;
   v=1,2,3 are distinct practice A, practice B, and timed counterparts. */
(() => {
  'use strict';
  const F=(n,d)=>{const gcd=(a,b)=>b?gcd(b,a%b):Math.abs(a);const g=gcd(n,d);return d/g===1?String(n/g):`${n/g}/${d/g}`;};
  const fmt=n=>String(Math.round(n*1000000)/1000000);
  const cash=n=>'$'+Number(n).toFixed(2);
  const comparison=['Column A is greater','Column B is greater','The quantities are equal','Cannot be determined'];
  const q=(prompt,answer,distractors,explanation,tip,extra={})=>({prompt,answer:String(answer),options:[String(answer),...distractors.map(String)],explanation,tip,...extra});
  const num=(prompt,a,explanation,tip,extra={})=>q(prompt,fmt(a),[fmt(a+1),fmt(a-1),fmt(a+10)],explanation,tip,extra);
  function cmp(prompt,a,b,result,explanation,tip,v=0,extra={}){
    if(v%2){[a,b]=[b,a];if(result<2)result=1-result;}
    return {prompt,columns:[a,b],answer:comparison[result],options:comparison,explanation,tip,fixedOrder:true,...extra};
  }
  const table=(headers,rows)=>({headers,rows});
  const bar=(labels,values,ylabel)=>({type:'bar',labels,values,ylabel});
  const line=(points,xmax,ymax,xlabel,ylabel,extra={})=>({type:'plot',points,xmax,ymax,xlabel,ylabel,...extra});
  const note={
    40:'Source correction: perimeter 60 and base 30 give equal sides of 15. Since 15 + 15 = 30, no non-degenerate triangle exists. Practice uses perimeter 80 with the same base; the original item should not count as a clear learner mistake.',
    48:'Source correction: 4 more than a mean of −2 is 2, not 4. The added number is 34, which is missing from the original choices. The old key and compilation gave 52; this practice corrects them.',
    60:'Source correction: the booklet states 1 gallon = 32 cups; a US gallon is 16 cups. To preserve the intended arithmetic without teaching a false conversion, this redo explicitly uses a 48-cup carton.',
    94:'Pattern clarification: the intended rule is to move 1 corner, then 2 corners, repeatedly, in the order upper-left → lower-left → lower-right → upper-right. This rule is stated explicitly for fair practice.',
    101:'Compilation correction: the source graph places B at (1, 3), not (2, 3). Its reflection in the x-axis is (1, −3).',
    111:'Source correction: exactly half of 11 integers is not a whole number, so the original wording is inconsistent and does not justify its answer. This corrected median exercise explicitly gives the two middle values of an even-sized set.',
    114:'Source correction: events on different draws are not complements; both can occur. The complement of green on a draw is not-green on that same draw. Practice fixes the wording.',
    117:'Source correction: odd on the first draw and even on a second draw are not complementary events. Odd and even on the same draw are complements. Practice fixes the wording.'
  };
  function build(id,v){
    const pick=(...xs)=>xs[v];
    switch(id){
      case 1:{const cups=pick(7,12,18,24),d=pick(3,3,4,4),e=pick(4,6,6,8);const left=cups*(1-1/d-1/e);return q(`${cups} equal cups are full of water. Fred uses 1/${d} of each full cup and Janice uses 1/${e} of each full cup. Approximately how many full cups remain?`,Math.round(left),[Math.round(left)+1,Math.round(left)+2,Math.round(left)+3],`Each cup keeps 1 − 1/${d} − 1/${e}. Multiply by ${cups}: about ${fmt(left)} cups, nearest to ${Math.round(left)}.`, 'Both fractions refer to the original full cup. Subtract them before multiplying.');}
      case 2:{const cents=pick(148,163,178,193),dp=Array(cents+1).fill(Infinity);dp[0]=0;for(let i=1;i<=cents;i++)for(const c of [1,10,25])if(i>=c)dp[i]=Math.min(dp[i],dp[i-c]+1);const target=pick(9,10,9,10);return cmp(`Rosa receives ${cash(cents/100)} in quarters (25¢), dimes (10¢), and pennies (1¢) only.`, 'Smallest possible number of coins',String(target),dp[cents]>target?0:dp[cents]<target?1:2,`The minimum is ${dp[cents]} coins. Compare ${dp[cents]} with ${target}.`,'Try the largest coins, then check whether replacing a quarter can reduce the total.',v);}
      case 3:{const a=5+v,b=9+v;return cmp('Compare the two products.',`(4 × 10^${a})(9 × 10^${b})`,`(6 × 10^${a-3})(6 × 10^${b+3})`,2,`Both coefficients multiply to 36; both exponents add to ${a+b}.`,'Multiply coefficients and add exponents.',v);}
      case 4:{const lower=-5-v,as=Array.from({length:3+v},(_,i)=>lower+1+i),bs=[-1,0,1,2];const products=new Set(as.flatMap(a=>bs.map(b=>a*b)));let impossible=-5-v;while(products.has(impossible))impossible--;const good=[-3,2,0];return q(`a and b are integers with ${lower} < a < −1 and −2 < b < 3. Which is NOT a possible value of ab?`,impossible,good,`List a: ${as.join(', ')} and b: −1, 0, 1, 2. None of their products is ${impossible}.`,'Strict inequalities exclude the endpoints. Make a small list.');}
      case 5:{const a=pick(.9,1.1,1.3,1.5),sub=pick('4/5','5/5','6/5','7/5'),d=pick(.5,.4,.25,.2),e=pick(.75,.8,.5,.6);return cmp('Compare.',`(${a} − ${sub}) ÷ ${d}`,`(1/2 − 0.4) ÷ ${e}`,0,`The numerators are both 0.1. Dividing a positive number by the smaller denominator gives the larger result.`,'Simplify the numerators first.',v);}
      case 6:{const total=136+20*v,target=7+v;return cmp(`Pencils come in packs of 4, 12, or 20. Mrs. White buys exactly ${total} pencils.`, 'Fewest packs she could buy',String(target),0,`${5+v} packs of 20 plus 3 packs of 12 give ${total} in ${8+v} packs. ${target} packs would hold at most ${target*20}, and reducing that total by 4 is impossible: each swap reduces it by 8 or 16.`,'Start with the largest pack and check the leftover.',v);}
      case 7:{const a=pick(.16,.25,.36,.49),b=pick(.9,.8,.7,.81);return cmp('Compare the principal square roots.',`√${a}`,`√${b}`,1,`For nonnegative numbers, square roots keep the same order. ${a} < ${b}.`,'You do not need to calculate both roots.',v);}
      case 8:{const r=pick('5/4','7/5','9/7','11/9'),s=pick('9/8','6/5','8/7','10/9');return q(`a and b are positive. Which expression is greatest?`,`(a/b) × ${r}`,[`(a/b) ÷ ${s}`,`(a/b) ÷ ${r}`,`(a/b) × ${s}`],`The common factor a/b is positive. ${r} is the largest of the four effective multipliers.`,'Division by a fraction multiplies by its reciprocal.');}
      case 9:{const n=4+v,m=2+v,total=2**n*3**m;return num(`If 2^n × 3^m = ${total}, where n and m are nonnegative integers, what is n + m?`,n+m,`${total} = 2^${n} × 3^${m}; ${n} + ${m} = ${n+m}.`,'Divide by 2 repeatedly, then by 3.');}
      case 10:{const a=2+v;return cmp('k > 1.',`(1/k)^${a}`,`(1/k)^${a+1}`,0,'1/k lies between 0 and 1. Multiplying by it again makes a positive number smaller.','Powers of a fraction between 0 and 1 get smaller.',v);}
      case 11:{const start=pick(42,50,60,80),p=pick(150,120,75,50);return num(`A population of ${start} fruit flies increases by ${p}%. What is the new population?`,start*(1+p/100),`${start} × (1 + ${p}/100) = ${fmt(start*(1+p/100))}.`,'An increase of p% means keep the original AND add p%.');}
      case 12:{const price=12+4*v,tax=5+v,shipping=4+v;return q(`Sweatshirts cost ${cash(price)} each plus ${tax}% sales tax per shirt. Every order has the same shipping fee. What is that fee?`,cash(shipping),[cash(shipping+1),cash(price),cash(price*(1+tax/100))],`One taxed shirt costs ${cash(price*(1+tax/100))}. Subtract that from ${cash(price*(1+tax/100)+shipping)} to get ${cash(shipping)}.`,'Use the one-shirt order.',{table:table(['Shirts','Order total'],[1,4,2,3].map(n=>[n,cash(n*price*(1+tax/100)+shipping)]))});}
      case 13:{const price=100+50*v,p=10+5*v;return cmp(`A bicycle originally costs ${cash(price)}.`, `Amount saved by one ${2*p}% discount`,`Amount saved by two successive ${p}% discounts`,0,`The second ${p}% discount applies to a smaller price. Combined savings are ${2*p-p*p/100}%, less than ${2*p}%.`,'Successive percentages multiply; they do not add.',v);}
      case 14:{const a=20+10*v,b=25+5*v;return cmp('Compare travel times.',`${a} miles at ${2*a} mph`,`${b} miles at ${2*b} mph`,2,'Time = distance ÷ speed. Both trips take 1/2 hour.','Compare distance/speed, not distance alone.',v);}
      case 15:{const price=800+200*v,p=25+5*v;return cmp(`A laptop costs ${cash(price)} before a ${p}% Friday markup. On Saturday it returns to its original price.`, 'Percent decrease from Friday to Saturday',`${p}%`,1,`The decrease is measured from the higher Friday price: ${p}/(100 + ${p}) × 100 ≈ ${fmt(p/(100+p)*100)}%.`,'Percent change uses the starting price as its denominator.',v);}
      case 16:{const lead=1+v,slow=5+v,fast=slow+lead;return cmp(`Charlie is ${lead} mile(s) ahead, running ${slow} mph. Garret follows at ${fast} mph.`, 'Time until Garret catches Charlie','1 hour',2,`Closing speed = ${fast} − ${slow} = ${lead} mph. Time = ${lead}/${lead} = 1 hour.`,'Use the difference in speeds.',v);}
      case 17:{const y=12+4*v,r=4+v;return cmp(`A bag contains yellow, orange, and green marbles. Yellow:green = ${r}:5, and there are ${y} yellow marbles.`, 'Number of orange marbles',String(15+v),3,'No information limits the number of orange marbles. It could be smaller, equal, or larger.','Do not use a ratio for a color it does not mention.',v);}
      case 18:{const goalA=70+10*v,goalB=120+20*v,a=.6*goalA,b=.75*goalB;return cmp('Two grades collect cans toward different goals.', 'Cans still needed by Grade 6','Cans still needed by Grade 7',1,`Grade 6: ${a}/0.60 − ${a} = ${fmt(goalA-a)}. Grade 7: ${b}/0.75 − ${b} = ${fmt(goalB-b)}.`,'Find each whole goal before finding what remains.',v,{table:table(['Grade','Collected','Percent of goal'],[[6,a,'60%'],[7,b,'75%']])});}
      case 19:{const pay=1000+200*v,p=15+5*v;return cmp(`Kareem and Alyssa each earn ${cash(pay)} weekly. Kareem saves ${p}%; Alyssa saves 1/8.`, 'Kareem’s savings over four weeks','Alyssa’s savings over four weeks',0,`1/8 = 12.5%, less than ${p}%. Both have the same income and number of weeks.`,'When the wholes match, just compare the fractions.',v);}
      case 20:{const n=7+v;return num(`The points for 1, 2, 3 correct answers are 2, 4, 8. Points double with each correct answer. How many correct answers earn ${2**n} points?`,n,`The score after n correct answers is 2^n. Since 2^${n} = ${2**n}, the student answered ${n} correctly.`,'Count the doublings, starting with 2 as the first score.');}
      case 21:{const b=3+v,days=7-v;const expr=`1 + ${Array.from({length:days},(_,i)=>`${b}^${i+1}`).join(' + ')}`;return q(`One student knows a secret. On day 1 the student tells ${b} new people. Each new group tells ${b} different new people per person on the next day. Which expression counts everyone who knows it after ${days} days?`,expr,[`1 + ${b}^${days}`,`${b}^${days}`,Array.from({length:days},(_,i)=>`${b}^${i+1}`).join(' + ')],`Count the original student (1), then every day's new group: ${expr}.`,'Include the starting person and every generation, not only the last.');}
      case 22:{const a=4+2*v;return cmp('Compare slopes.',`Slope of ${a}x − 2y = 10`,`Slope through (4, 4) and (2, ${8+2*v})`,0,`First slope = ${a}/2 = ${a/2}. Second = (${8+2*v} − 4)/(2 − 4) = ${-(2+v)}.`,'Isolate y for an equation; use rise/run for points.',v);}
      case 23:{const n=10+v;return num(`A trivia game awards 1, 2, 4, 7, 11 points for 1–5 correct answers. The increments continue +1, +2, +3, +4, … . How many points for ${n} correct answers?`,1+n*(n-1)/2,`Start at 1 and add 1 through ${n-1}: 1 + ${n*(n-1)/2} = ${1+n*(n-1)/2}.`,'Write the differences between consecutive terms.');}
      case 24:{const mult=2+v,twenty=20+10*v,diff=60+20*v;return q(`Theresa has T bills worth $${twenty} each and ${mult} times as many $5 bills. The $${twenty} bills are worth $${diff} more than the $5 bills. Which equation models this?`,`${5*mult}T = ${twenty}T − ${diff}`,[`${mult}T = T − ${diff}`,`${5*mult}T = ${twenty}T + ${diff}`,`${mult}T = T + ${diff}`],`The $5 bills total 5 × ${mult}T = ${5*mult}T. This is $${diff} less than ${twenty}T.`,'Turn each bill count into dollars before comparing.');}
      case 25:{const start=100+50*v,b=2+v;const terms=Array.from({length:4},(_,i)=>i?`${start} × ${b}^${i}`:`${start}`);return q(`Will deposits $${start} in January, then ${b} times the previous month's deposit each month. With no withdrawals or interest, which expression is the total deposited January through April?`,terms.join(' + '),[`${start} × ${b}^3`,`${start} × ${b}^4`,terms.map((_,i)=>`${start} × ${b}^${i+1}`).join(' + ')],`The four deposits are ${[0,1,2,3].map(i=>cash(start*b**i)).join(', ')}. Add all four.`,'January is exponent 0, not exponent 1.');}
      case 26:{const m=-3-v;return cmp('Compare slopes.',`Slope of y = ${m}x − 6`,`Slope through (−5, 4) and (−8, ${10+3*v})`,1,`The second slope is (${10+3*v} − 4)/(−8 + 5) = ${-2-v}. This is greater than ${m}.`,'Among negative numbers, the one nearer zero is greater.',v);}
      case 27:return cmp(`a < 0 and b < 0. Compare the expressions with coefficient ${v+1}.`,`a + ${v+1}b`,`a − ${v+1}b`,1,'Adding a negative amount makes a smaller result. Subtracting that negative amount makes a larger result.','Track the sign of b.',v);
      case 28:{const n=pick(25,26,29,32),shapes=['heart','smile','crescent','cloud','plus'],a=shapes[(n-1)%5];return q(`The pattern repeats: heart, smile, crescent, cloud, plus. What is shape number ${n}?`,a,shapes.filter(x=>x!==a).slice(0,3),`${n} divided by 5 leaves remainder ${n%5}. Remainder 0 means the fifth shape; otherwise use the remainder.`,'Use the remainder after dividing by the pattern length.');}
      case 29:{const k=6+v;return cmp('a and b are positive integers.',`−${k}(a − b)`,`−${k}a − ${k}b`,0,`Distribute: −${k}(a − b) = −${k}a + ${k}b. The difference from −${k}a − ${k}b is ${2*k}b > 0.`,'A negative times a negative becomes positive.',v);}
      case 30:{const side=500+100*v;return cmp(`Mary compares the two right-angle routes shown. Each route returns to its starting dot.`, 'Distance saved by the stair-step route',`${200+50*v} ft`,1,`Both routes total ${4*side} ft: their horizontal lengths total ${2*side} and vertical lengths total ${2*side}. Saved distance is 0.`,'Add horizontal segments together and vertical segments together.',v,{visual:{type:'routes',width:side,height:side}});}
      case 31:return cmp(`R and T are endpoints of a ${10+5*v} cm segment. S is somewhere strictly between them.`, 'RS','ST',3,'S could be near R, in the middle, or near T. All three comparisons are possible.','Between does not mean midpoint.',v);
      case 32:{const x=v?String(2+v):'x';return q(`A square has side ${x} mm. An isosceles right triangle is attached along one full side, with both perpendicular legs ${x} mm. What is their total area?`,v?`${1.5*(2+v)**2} mm²`:'1.5x² mm²',v?[`${(2+v)**2} mm²`,`${2*(2+v)**2} mm²`,`${3*(2+v)**2} mm²`]:['3x mm²','2x² mm²','3x² mm²'],`Square area is ${x}²; triangle area is (1/2)${x}². Total is 1.5 × ${x}².`,'Split a composite figure into familiar shapes.',{visual:{type:'squareTriangle',label:x}});}
      case 33:{const r=6+v;return cmp('Compare the lengths in meters.',`Radius of a circle with area ${r*r}π m²`,`Diameter of a circle with circumference ${2*r}π m`,1,`Area πr² gives radius ${r}. Circumference πd gives diameter ${2*r}.`,'Do not confuse radius with diameter.',v);}
      case 34:{const h=6+v,b=14+2*v;return cmp('Compare areas.',`Rectangle ${h} m by ${b} m`,`Triangle with base ${b} m and height ${2*h} m`,2,`Rectangle: ${h} × ${b}. Triangle: (1/2) × ${b} × ${2*h}. Both equal ${h*b} m².`,'The triangle has twice the height but half the area formula.',v);}
      case 35:{const k=3+v;return q(`A large cube has side length ${k} times the side of a small cube. What is the small:large surface-area ratio?`,`1:${k*k}`,[`1:${k**3}`,`1:${k}`,`1:${2*k*k}`],`Surface area is 6s². The side factor ${k} is squared: ${k*k}.`,'Lengths scale by k, areas by k², volumes by k³.');}
      case 36:return cmp(`Each grid segment represents ${F(1,4+v)} mile. Compare the two right-angle closed routes.`, 'Length of Path A','Length of Path B',2,'The indent changes the shape, but the total horizontal and vertical travel stays the same. Each route has 24 grid segments.','Count segments, not the area inside.',v,{visual:{type:'routes',width:5,height:7,grid:true}});
      case 37:{const outer=10+2*v,inner=6+2*v,border=outer*outer-inner*inner,target=4+v;return cmp(`A square of side ${outer} m surrounds a smaller square with a uniform border. The border's area is ${border} m².`,`${target} m`,'Width of the border',0,`Inner area = ${outer}² − ${border} = ${inner*inner}, so inner side = ${inner}. Border width = (${outer} − ${inner})/2 = 2 m.`,'Subtract areas, take the square root, then divide the side difference by 2.',v,{visual:{type:'border',outer,innerLabel:'?'}});}
      case 38:{const angle=100+10*v;return q('Triangle ABC has an acute angle A. Which value could be B + C?',`${angle}°`,['80°','90°','180°'],`B + C = 180° − A. Since 0° < A < 90°, the sum is strictly between 90° and 180°.`,'Use the triangle angle sum.');}
      case 39:{const f=1+v;return cmp(`A triangle has sides ${4*f}, ${6*f}, and ${8*f} inches.`, 'Longest side after scaling by 2/3','Shortest side after scaling by 4/3',2,`${8*f} × 2/3 = ${4*f} × 4/3 = ${F(16*f,3)} inches.`,'Use the matching longest or shortest original side.',v);}
      case 40:{const base=30+6*v,side=20+4*v,bound=15+3*v;return cmp(`Corrected exercise: an isosceles triangle has perimeter ${2*side+base} inches and base ${base} inches. h is the altitude to that base.`, 'h',`${bound} inches`,1,`Each equal side is ${side}. Half the base is ${base/2}. Thus h² = ${side}² − ${base/2}² = ${side*side-base*base/4}, less than ${bound}² = ${bound*bound}. So h < ${bound}.`,'The altitude splits an isosceles triangle into two right triangles.',v);}
      default: return buildLater(id,v);
    }
  }
  function buildLater(id,v){
    const pick=(...xs)=>xs[v];
    switch(id){
      case 41:{const vals=[7.5,4,6,9.5,10,8].map(x=>x+v);return num('The chart shows rainfall in six months. What is the mean monthly rainfall, in cm?',7.5+v,`Add the six amounts: ${45+6*v}. Divide by 6 to get ${7.5+v} cm.`,'Mean = total ÷ number of values.',{visual:bar(['Jan','Feb','Mar','Apr','May','Jun'],vals,'Rainfall (cm)')});}
      case 42:{const n=7+v,mean=9+v,drop=3;const a=(n+1)*(mean-drop)-n*mean;return num(`A set of ${n} numbers has mean ${mean}. One number is added, lowering the mean by ${drop}. What number is added?`,a,`Old sum = ${n} × ${mean} = ${n*mean}. New sum = ${n+1} × ${mean-drop} = ${(n+1)*(mean-drop)}. Subtract: ${a}.`,'Convert both means into sums.');}
      case 43:{const x=60+10*v,m=5+v,b=150,total=m*x+b;return q(`Using the best-fit line, what is the average cost PER ITEM for an order of ${x} items?`,cash(total/x),[cash(m),cash(total),cash(total/x+2)],`The line predicts a total of ${cash(total)}. Divide by ${x} items: ${cash(total/x)} per item.`,'Read the total first, then divide by the item count.',{visual:line([[0,b],[100,m*100+b]],100,1200,'Items','Total cost ($)',{scatter:true})});}
      case 44:{const days=4+v,m=150+25*v,b=150,total=m*days+b;return q(`Using the best-fit line, what is the average DAILY cost of renting the cabin for ${days} days?`,cash(total/days),[cash(m),cash(total),cash(total/days+50)],`Predicted total = ${cash(total)}. Average per day = ${cash(total)} ÷ ${days} = ${cash(total/days)}.`,'Average cost is total cost divided by days; it is not necessarily the slope.',{visual:line([[0,b],[18,m*18+b]],18,5000,'Days','Total cost ($)',{scatter:true})});}
      case 45:{const values=[4,8,10,12,2,4],labels=Array.from({length:6},(_,i)=>i+v);return num('The frequency chart describes 40 children. What is the median number of sports played?',2+v,`The median is the average of positions 20 and 21. Both fall in the ${2+v}-sports bar.`,'Cumulative frequencies locate the middle; do not take the median of bar heights.',{visual:bar(labels,values,'Number of children')});}
      case 46:{const n=5+v,a=10+v,b=12+v,added=(n+1)*b-n*a,target=16+3*v;return cmp(`${n} numbers average ${a}. Adding one number gives a mean of ${b}.`,'Number added',String(target),added>target?0:added<target?1:2,`Added number = ${n+1} × ${b} − ${n} × ${a} = ${added}.`,'New total minus old total gives the missing number.',v);}
      case 47:{const start=10*v;return cmp('A histogram groups 18 workers’ hourly wages into intervals. Exact wages within each interval are not given.','Mode of the individual wages','Mean of the individual wages',3,'The tallest interval is not an exact mode. Different exact values inside the intervals can change the relationship.','Grouped intervals hide exact data values.',v,{visual:bar(Array.from({length:6},(_,i)=>`${start+10*i}–${start+10*i+9}`),[2,4,6,3,1,2],'Workers')});}
      case 48:{const n=8+v,mean=-2+v,rise=4+v,a=(n+1)*(mean+rise)-n*mean;return num(`A set of ${n} numbers has mean ${mean}. What number must be added so that the new mean is ${rise} MORE than the original mean?`,a,`New mean = ${mean} + ${rise} = ${mean+rise}. Added number = (${n+1})(${mean+rise}) − (${n})(${mean}) = ${a}.`,'First calculate the new mean; “more than” is an increase, not the final mean.');}
      case 49:return cmp(`Each number in a set of ${5+2*v} numbers is increased by ${2+v}.`,'New median','New mean',3,`Both measures increase by ${2+v}, but we do not know which was greater before.`,'A common shift preserves an unknown relationship; it does not determine it.',v);
      case 50:{const m=60+3*v,n=55+2*v;return num(`The mean temperature Monday–Thursday is ${m}°F. The mean Monday–Friday is ${n}°F. What is Friday’s temperature, in °F?`,5*n-4*m,`Five-day total minus four-day total: 5 × ${n} − 4 × ${m} = ${5*n-4*m}.`,'Use totals when one extra day changes the average.');}
      case 51:return cmp(`A box plot for 40 ages has minimum ${10+v}, lower quartile ${15+v}, median ${25+v}, upper quartile ${45+v}, and maximum ${60+v}.`,'Range of ages','Mode of ages',3,`The range is 50, but the box plot does not tell which exact age occurs most often. The mode could fall on either side of 50.`,'A box plot shows spread and quartiles, not frequencies of individual values.',v,{visual:{type:'box',values:[10,15,25,45,60].map(x=>x+v)}});
      case 52:{const vals=[8,9,5,7,6,10,4].map(x=>x+v);return cmp('The table shows Brandon’s running distances last week.','Mean daily miles','Saturday’s miles',1,`Total = ${49+7*v}; mean = ${7+v}. Saturday is ${10+v}, which is greater.`,'Divide the total by all seven days.',v,{table:table(['Day','Miles'],['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map((d,i)=>[d,vals[i]]))});}
      case 53:{const n=9+v;return cmp(`Cards numbered 1 through ${n} are equally likely to be drawn.`,'Probability of an even number','Probability of an odd number',n%2?1:2,`There are ${Math.floor(n/2)} even and ${Math.ceil(n/2)} odd cards out of ${n}.`,'Count favorable cards before comparing probabilities.',v);}
      case 54:{const n=5+2*v,e=Math.floor(n/2);return q(`A two-number lock code is made by independently choosing each number from 1 through ${n}. Repeats are allowed. What is the probability both numbers are even?`,F(e*e,n*n),[F(e,n),F(1,n*n),F(e*2,n)],`Each choice has probability ${e}/${n}. Multiply: (${e}/${n})² = ${F(e*e,n*n)}.`,'Independent events: multiply their probabilities.');}
      case 55:{const sides=6+2*v;return cmp(`Two fair dice numbered 1 through ${sides} are rolled.`,'Probability of an odd product','Probability of an even product',1,'An odd product needs two odd numbers: (1/2)(1/2) = 1/4. The other 3/4 give an even product.','Find the smaller event, then subtract from 1.',v);}
      case 56:{const b=3+v,blue=6+v,r=4+2*v,g=5+2*v;return cmp(`A basket has ${b} black, ${blue} blue, ${r} red, and ${g} green markers. Two are drawn without replacement.`,'Probability of one red and one green','Probability of one black and one blue',r*g>b*blue?0:1,`The shared denominator and factor 2 cancel. Compare ${r} × ${g} = ${r*g} with ${b} × ${blue} = ${b*blue}.`,'For an unordered pair of different colors, compare the products of their counts.',v);}
      case 57:{const sides=8+v,a=6+v,b=5+v;return cmp(`An equal-sector spinner numbered 1 through ${sides} is spun twice.` ,`Probability the sum is ${a}`,`Probability the sum is ${b}`,0,`There are ${a-1} ordered pairs making ${a}, and ${b-1} making ${b}, out of ${sides*sides} pairs.`,'Count ordered pairs, including reversed pairs.',v);}
      case 58:{const a=9876+111*v,b=6789+222*v;return num(`What is ${a} + ${b}?`,a+b,`Align place values and add with regrouping: ${a} + ${b} = ${a+b}.`,'Keep ones, tens, hundreds, and thousands in their own columns.');}
      case 59:{const numerator=16+v;return q(`Find n: 3 ${1+v}/5 ÷ 1 2/3 = n.`,F(numerator*3,25),[F(numerator*5,15),F(numerator+5,8),F(numerator*3+1,25)],`3 ${1+v}/5 = ${numerator}/5 and 1 2/3 = 5/3. Multiply by 3/5: (${numerator}/5)(3/5) = ${F(numerator*3,25)}.`,'Convert both mixed numbers first, then flip only the divisor.');}
      case 60:{const total=48+8*v;return num(`A carton contains ${total} cups of juice. Allison pours six small glasses of 2 cups each and four large glasses of 3 cups each. How many MORE full small glasses can she pour?`,(total-24)/2,`Used = 6 × 2 + 4 × 3 = 24 cups. Remaining = ${total-24}; divide by 2 to get ${(total-24)/2}.`,'Subtract both amounts poured before dividing by the small-glass size.');}
      case 61:{const a=27+4*v,b=14+3*v;return q(`What is (${6+v} 3/4) × (${4+v} 2/3)?`,F(a*b,12),[F(a*b+12,12),F(a*b-12,12),F(a+b,7)],`Convert: ${a}/4 × ${b}/3 = ${a*b}/12 = ${F(a*b,12)}.`,'Convert mixed numbers to improper fractions first.');}
      case 62:{const lo=1+v,hi=5+v;return q(`Which number-line description represents all INTEGERS no less than ${lo} and no more than ${hi}?`,`Separate filled dots at ${Array.from({length:5},(_,i)=>lo+i).join(', ')}`,[`A solid segment from ${lo} to ${hi}`,`Separate dots at ${lo+1}, ${lo+2}, ${hi-1}`,`All points to the right of ${hi}`],`Inclusive inequalities include both endpoints. Integers are separate whole-number points, not a continuous segment.`,'Check two things: endpoints and whether the values are discrete.');}
      case 63:{const a=.0964+.008*v,b=.8;return q(`What is ${fmt(a)} ÷ ${b}?`,fmt(a/b),[fmt(a/b*10),fmt(a/b*100),fmt(a/b+.0045)],`Multiply both numbers by 10: ${fmt(a*10)} ÷ 8 = ${fmt(a/b)}.`,'Move both decimal points the same number of places.');}
      case 64:{const a=489+100*v,b=812,den=5000;const answer=(500+100*v)*800/den;return q(`Approximately what is (${a} × ${b}) ÷ ${den}?`,answer,[answer*10,answer*100,answer*1000],`Round to ${500+100*v} × 800 ÷ 5000 = ${answer}.`,'Estimate the size first so an extra zero cannot fool you.');}
      case 65:{const a=2.3+v,b=5.9,answer=fmt(a+b/10);return q(`Write ${fmt(a)} × 10^5 + 5.9 × 10^4 in scientific notation.`,`${answer} × 10^5`,[`${answer} × 10^4`,`${fmt(a+b)} × 10^5`,`${fmt(a+b)} × 10^9`],`Rewrite 5.9 × 10^4 as 0.59 × 10^5. Then add ${fmt(a)} + 0.59 = ${answer}.`,'Match powers of ten before adding coefficients.');}
      case 66:{const d=4+v;return q(`What is 1/${d} + (3/8) × (4/9)?`,F(6+d,6*d),[F(1,d+6),F(6+d+1,6*d),F(6+d,3*d)],`Multiply first: (3/8)(4/9) = 1/6. Then 1/${d} + 1/6 = ${F(6+d,6*d)}.`,'Multiplication comes before addition.');}
      case 67:{const factor=1.5+.25*v;return q(`Today Josh’s homework INCREASES BY ${factor} times yesterday’s amount. By what percent does it increase?`,`${factor*100}%`,[`${(factor-1)*100}%`,`${(factor+1)*100}%`,`${factor}%`],`The added amount is ${factor} of the old amount. ${factor} × 100% = ${factor*100}%.`,'“Increases by” describes the added part; “increases to” describes the final total.');}
      case 68:{const d=24+3*v;return num(`If N/${d} = 14/21, what is N?`,d*2/3,`14/21 = 2/3. N = ${d} × 2/3 = ${d*2/3}.`,'Reduce the fraction before cross-multiplying.');}
      case 69:{const p=45+15*v;return q(`${p}% of a class pass the oral exam. Of those, 2/3 also pass the written exam. What fraction of the WHOLE class pass both?`,F(p*2,300),[F(p,100),F(p,300),F(p*2,100)],`(${p}/100) × (2/3) = ${F(p*2,300)}.`,'“Of those” means multiply, not add.');}
      case 70:{const nights=14+v,price=8+v,estimate=Math.round((150*nights*price-2750)/1000)*1000;return q(`A show costs between $2,500 and $3,000 to produce. It runs for ${nights} nights, with 100–200 audience members per night. Tickets cost $${price}. Using the midpoints as estimates, approximately what is the profit, to the nearest $1,000?`,cash(estimate),[cash(estimate-5000),cash(estimate+5000),cash(estimate+10000)],`Use 150 people and $2,750 cost. Revenue = 150 × ${nights} × ${price} = $${150*nights*price}. Profit ≈ $${150*nights*price-2750}, nearest to ${cash(estimate)}.`,'Profit = revenue − cost. This is an estimate, not an exact prediction.');}
      case 71:{const p=80-10*v;return q(`2/5 of the students are girls, and ${p}% of the girls play a sport. What percent of ALL students are girls who play a sport?`,`${.4*p}%`,[`${p}%`,`${40+p}%`,`${.2*p}%`],`(2/5) × (${p}/100) = ${fmt(.4*p/100)} = ${.4*p}%.`,'Keep track of the whole: all students, not just girls.');}
      case 72:{const d=15+3*v;return q('The distance–time graph shows a walk. What is the walking speed in miles per hour?',`${d/4} mph`,[`${d/2} mph`,`${d} mph`,`${d/4+1} mph`],`Speed = distance ÷ time = ${d} ÷ 4 = ${d/4} mph.`,'Use a clear point on the line.',{visual:line([[0,0],[2,d/2],[4,d]],4,d,'Hours','Miles')});}
      case 73:{const dist=6000+3000*v,speed=30;return num(`At ${speed} km/h, how many minutes does a cyclist need to travel ${dist} meters?`,dist/1000/speed*60,`${dist} m = ${dist/1000} km. Time = ${dist/1000}/${speed} hour; multiply by 60 = ${dist/1000/speed*60} minutes.`,'Convert meters to kilometers before using km/h.');}
      case 74:{const denom=4+v,numer=denom-1,p=10+10*v;return q(`Quinn answers ${numer}/${denom} of a test. She gets ${p}% of the questions she answers wrong. What fraction of the ENTIRE test does she answer incorrectly?`,F(numer*p,denom*100),[F(p,100),F(numer,denom),F(denom*100-numer*p,denom*100)],`(${numer}/${denom}) × (${p}/100) = ${F(numer*p,denom*100)}.`,'Only the answered part can contribute to this wrong-answer fraction.');}
      case 75:{const b=10+5*v;return q(`In the model y = ${250+10*v}x + ${b}, x is hours and y is calories. What does ${b} represent?`,`The model predicts ${b} calories when x = 0`,[`The number of calories per hour`,`The number of hours needed to burn one calorie`,`The maximum possible number of calories`],`Set x = 0: y = ${b}. It is the model's starting value.`,'The constant term is the value when the input is zero.');}
      case 76:{const a=4+v,b=7+v;return q(`What is the slope of ${a}x − ${b}y = −14?`,F(a,b),[F(b,a),String(a),`−${F(a,b)}`],`Rearrange to y = (${a}/${b})x + 14/${b}. The coefficient of x is the slope.`,'Isolate y and read the coefficient of x.');}
      case 77:{const a=7+2*v,b=2+v;return num(`If x − ${a} + ${b} = y, what is x − y?`,a-b,`y = x − ${a-b}, so x − y = ${a-b}.`,'Combine the constants first.');}
      case 78:{const d=2+v,c=3+v;return q(`Which equation is equivalent to x = y/${d} − ${c}?`,`y/${d} = x + ${c}`,[`y + ${c} = x/${d}`,`${d}x + y = ${c}`,`${d}(x + y) = ${c}`],`Add ${c} to both sides: x + ${c} = y/${d}.`,'Do the same operation to both sides.');}
      case 79:{const b=9+v,x=10,y=b-4,intercept=y-25;return q(`The graphed line passes through (0, ${b}) and (10, ${y}). Which equation is perpendicular to it through (10, ${y})?`,`y = (5/2)x − ${-intercept}`,[`y = (−2/5)x + ${b}`,`y = (5/2)x + ${-intercept}`,`y = (−5/2)x + ${b}`],`Original slope = (${y} − ${b})/10 = −2/5. Perpendicular slope = 5/2. Use (${10}, ${y}): intercept = ${y} − 25 = ${intercept}.`,'Perpendicular slopes are negative reciprocals.',{visual:line([[0,b],[10,y],[b*2.5,0]],25,15,'x','y')});}
      case 80:{const a=5+v,x=-3-v,b=9;return q(`If ${a}x = −${b}y and x = ${x}, what is y?`,F(-a*x,b),[F(a*x,b),F(-b*x,a),F(b*x,a)],`Substitute: ${a}(${x}) = −${b}y. Divide both sides by −${b}: y = ${F(-a*x,b)}.`,'Substitute with parentheses to preserve the negative sign.');}
      case 81:{const a=5+v,b=2+v;return q(`What is the slope of ${a}x + ${b}y = 8?`,F(-a,b),[F(-b,a),F(a,b),F(b,a)],`y = (${F(-a,b)})x + ${F(8,b)}. The slope is ${F(-a,b)}.`,'Moving the x-term to the other side changes its sign.');}
      case 82:{const d=3+v,g=15+5*v;return q(`Jim starts with j dollars. He spends d dollars per day for ${d} days, then receives $${g}. Which expression is his new balance?`,`j − ${d}d + ${g}`,[`j − d + ${g}`,`j + ${d}d + ${g}`,`j − ${d}d − ${g}`],`Total spent = ${d}d. Subtract spending and add the gift.`,'Expenses subtract; gifts add.');}
      case 83:{const d=5+v,a=10+v,b=20+v;return q(`Which equation is equivalent to 2x/${d} = ${a}y − ${b}?`,`2x + ${d*b} = ${d*a}y`,[`2x = ${d*a}y − ${b}`,`2x + ${d*a}y = ${d*b}`,`2x = ${a}y − ${b}`],`Multiply EVERY term by ${d}: 2x = ${d*a}y − ${d*b}. Add ${d*b}.`,'Multiplication must reach every term, not just the first.');}
      case 84:{const k=2+v;return num(`Solve (p − ${k})/p = 4/3, with p ≠ 0.`, -3*k,`Cross-multiply: 3(p − ${k}) = 4p. Then 3p − ${3*k} = 4p, so p = ${-3*k}.`,'Use parentheses when cross-multiplying a numerator with subtraction.');}
      case 85:{const x0=8+v,y0=6+2*v,y1=2+2*v;return num(`A line has slope 2 and passes through (${x0}, ${y0}) and (x, ${y1}). Find x.`,x0-2,`2 = (${y1} − ${y0})/(x − ${x0}) = −4/(x − ${x0}). Thus x − ${x0} = −2 and x = ${x0-2}.`,'Keep the same point order in the numerator and denominator.');}
      default: return buildLast(id,v);
    }
  }
  function buildLast(id,v){
    switch(id){
      case 86:{const b=4+2*v,c=-6-2*v;return num(`If 2a = 3b − c, what is a when b = ${b} and c = ${c}?`,(3*b-c)/2,`2a = 3(${b}) − (${c}) = ${3*b-c}. Divide by 2 to get ${(3*b-c)/2}.`,'Subtracting a negative is addition.');}
      case 87:{const a=6+3*v,b=9,c=2+v;return q(`Which equation is equivalent to ${a}m = ${b}(n − ${c})?`,`n = (${F(a,b)})m + ${c}`,[`n = (${F(a,b)})m + ${b*c}`,`n = (${F(a,b)})m − ${c}`,`${a}m = ${b}n − ${c}`],`Divide by ${b}, then add ${c}: n = (${F(a,b)})m + ${c}.`,'Divide the whole equation before moving the constant.');}
      case 88:{const x=4+v,y=2*x;return q(`A line crosses the x-axis at ${x} and the y-axis at ${y}. What is its equation?`,`y = −2x + ${y}`,[`y = 2x + ${y}`,`y = (−1/2)x + ${x}`,`y = (1/2)x + ${x}`],`The points are (${x}, 0) and (0, ${y}). Slope = (0 − ${y})/${x} = −2; y-intercept = ${y}.`,'An x-intercept is a point with y = 0, not the constant term.');}
      case 89:{const fee=60+10*v,rate=30+10*v;return q(`A plumber charges a $${fee} equipment fee plus $${rate} per hour, billed in half-hour increments. Which description matches the graph of total cost?`,`Dots starting at (0, ${fee}), rising $${rate/2} every 0.5 hour`,[`Dots starting at (0, 0), rising $${rate/2} every 0.5 hour`,`Dots starting at (0, ${fee}), rising $${rate} every 0.5 hour`,`Dots starting at (0, ${fee}), rising $${rate/2} every 1 hour`],`At 0 hours the fee is $${fee}. Each half hour adds half the hourly rate: $${rate/2}.`,'Check both the starting value and the rise per time step.');}
      case 90:{const first=20+5*v,later=10+5*v,hours=2+v;return q(`An office costs $${first} per hour for the first ${hours} hours, then $${later} per additional hour. For whole-number h > ${hours}, which formula gives total cost T?`,`T = ${first*hours} + ${later}(h − ${hours})`,[`T = ${first} + ${later}(h − ${hours})`,`T = ${first*hours} + ${later}h`,`T = ${first*hours} + ${later}(h + ${hours})`],`The first part costs ${hours} × $${first} = $${first*hours}. Only h − ${hours} hours use the later rate.`,'Do not charge the later rate for hours already paid for.');}
      case 91:{const extra=5+3*v,diff=.1;return q(`Trina has q quarters and ${extra} more dimes than quarters. The quarters are worth $0.10 more than the dimes. Which equation models this?`,`0.10(q + ${extra}) + 0.10 = 0.25q`,[`0.10(q − ${extra}) + 0.10 = 0.25q`,`0.10q = 0.25(q + ${extra}) + 0.10`,`0.10(q + ${extra}) = 0.25q + 0.10`],`There are q + ${extra} dimes. Their value plus $0.10 equals the value of q quarters.`,'Write count × coin value for each group.');}
      case 92:{const x=6+3*v,y=3;return num(`Line m crosses the axes at (${x}, 0) and (0, ${y}). What is the slope of a line perpendicular to m?`,x/y,`Slope of m is −${y}/${x}. Its negative reciprocal is ${x}/${y} = ${x/y}.`,'Flip the fraction and reverse the sign.');}
      case 93:{const a=8+4*v,b=4;return q(`Which equation is equivalent to ${a}x = 2y − ${b}?`,`4(${a/4}x + 1) = 2y`,[`${a}x − 4 = 2y`,`${a/2}x + 4 = y`,`4(${a/4}x + 4) = 2y`],`Add 4: ${a}x + 4 = 2y. Factor out 4: 4(${a/4}x + 1) = 2y.`,'Expand each proposed answer to check it.');}
      case 94:{const corners=['upper-left','lower-left','lower-right','upper-right'];const n=6+v;let pos=0;const sequence=[corners[0]];for(let i=1;i<n;i++){pos=(pos+(i%2?1:2))%4;sequence.push(corners[pos]);}return q(`A dot moves around a square in this order: upper-left → lower-left → lower-right → upper-right → upper-left. Starting at upper-left, it moves 1 corner, then 2 corners, repeating those step sizes. What is its position in frame ${n}?`,corners[pos],corners.filter(c=>c!==corners[pos]),`Frames 1–${n}: ${sequence.join(', ')}.`,'Track the alternating step sizes, not just the last dot.',{visual:{type:'dots',corners:sequence.slice(0,n-1)}});}
      case 95:{const b=4+2*v;return q('What is the equation of the graphed line?',`y = −2x + ${b}`,[`y = 2x + ${b}`,`y = −${b}x + 2`,`y = ${b}x + 2`],`It crosses the y-axis at ${b} and falls 2 units per 1 unit right. So y = −2x + ${b}.`,'Read the intercept, then rise/run.',{visual:line([[-1,b+2],[b/2+2,-4]],7,12,'x','y',{xmin:-2,ymin:-5,grid:true})});}
      case 96:{const side=6+2*v;return q(`A circle is inscribed in a square of side ${side} cm. What is the area inside the square but outside the circle?`,`${side*side} − ${side*side/4}π cm²`,[`${side*side} − ${side*side}π cm²`,`${side*4} − ${side}π cm²`,`${side*side/2} − ${side*side/4}π cm²`],`Square area = ${side}² = ${side*side}. Radius = ${side/2}; circle area = ${side*side/4}π. Subtract.`,'The square side is the circle’s diameter.',{visual:{type:'circleSquare',label:side}});}
      case 97:{const s=6+v;return num(`A cube has surface area ${6*s*s} ft². What is its volume in ft³?`,s**3,`6s² = ${6*s*s}; s² = ${s*s}; s = ${s}. Volume = ${s}³ = ${s**3}.`,'Find a side length from surface area before cubing it.');}
      case 98:{const s=6+3*v,h=8+v;return num(`A square pyramid has base side ${s} inches and perpendicular height ${h} inches. Using V = (1/3)s²h, find its volume in cubic inches.`,s*s*h/3,`V = (1/3) × ${s}² × ${h} = ${s*s*h/3}.`,'Square the base side; do not multiply just side × height.');}
      case 99:{const area=24+8*v,n=3+v;return num(`A circle of area ${area} cm² is divided into 8 equal sectors; ${n} are shaded. What is the shaded area in cm²?`,area*n/8,`Each sector is ${area}/8 = ${area/8} cm². Multiply by ${n}: ${area*n/8} cm².`,'Shaded fraction × total area.',{visual:{type:'sectors',n:8,shaded:n}});}
      case 100:{const k=2+v;return num(`The two acute angles of a right triangle are x° and ${k}x°. Find x.`,90/(k+1),`x + ${k}x + 90 = 180. Thus ${k+1}x = 90 and x = ${90/(k+1)}.`,'The acute angles of a right triangle add to 90°.');}
      case 101:{const x=1+v,y=3+v;return q(`Triangle ABC is shown. If it is reflected across the x-axis, what are the new coordinates of B?`,`(${x}, −${y})`,[`(−${x}, ${y})`,`(−${x}, −${y})`,`(${y}, −${x})`],`B is (${x}, ${y}). Reflection in the x-axis keeps x and negates y: (${x}, −${y}).`,'Across the x-axis, only y changes sign.',{visual:line([[-2,2],[x,y],[2,-2],[-2,2]],6,7,'x','y',{xmin:-4,ymin:-4,grid:true,labels:['A','B','C','']})});}
      case 102:{const feet=6+v,inch=3,h=4+2*v;return num(`A triangular window has base ${feet} feet ${inch} inches and height ${h} feet. What is its area in square feet? (12 inches = 1 foot.)`,(feet+.25)*h/2,`${feet} ft 3 in = ${feet+.25} ft. Area = (1/2) × ${feet+.25} × ${h} = ${(feet+.25)*h/2}.`,'3 inches is 1/4 foot, not 0.3 foot.');}
      case 103:{const a=5+v,x=20+v,sa=4*a*x+2*a*a;return num(`A rectangular prism has dimensions x cm, ${a} cm, and ${a} cm. Its surface area is ${sa} cm². Find x.`,x,`2(${a}x + ${a}x + ${a*a}) = ${sa}. So ${4*a}x = ${sa-2*a*a} and x = ${x}.`,'Surface area adds all six faces, including the two ends.');}
      case 104:{const names=[['A','B','C','D'],['P','Q','R','S'],['W','X','Y','Z'],['J','K','L','M']][v];const [a,b,c,d]=names;return q(`Trapezoid ${names.join('')} has ${a}${b} parallel to ${d}${c}. Which extra fact proves it is isosceles?`,`Angles ${d} and ${c} are equal`,[`${a}${b} is parallel to ${d}${c}`,`Angles ${a} and ${d} sum to 180°`,`${a}${d} is perpendicular to ${b}${c}`],`Equal angles on the same base identify an isosceles trapezoid. The parallel sides and same-leg supplementary angles hold in any trapezoid.`,'Use a fact special to isosceles trapezoids, not all trapezoids.',{visual:{type:'trapezoid',names,variant:v}});}
      case 105:{const w=5+v,h=3+v;return q(`A quadrilateral has four right angles and adjacent sides ${w} cm and ${h} cm. Which is it NOT?`,'Rhombus',['Rectangle','Parallelogram','Quadrilateral'],`It is a rectangle, so also a parallelogram and quadrilateral. Its adjacent sides differ, so it is not a rhombus.`,'A rhombus must have all four sides equal.',{visual:{type:'rectangle',w,h}});}
      case 106:{const multiplier=1+v*.25;return q('From the scatter plot’s overall trend, approximately how much would a 1,000 ft² home cost?',cash(80000*multiplier),[cash(40000*multiplier),cash(60000*multiplier),cash(100000*multiplier)],`Near 1,000 ft², the trend is around ${cash(80000*multiplier)}. Use the overall cluster rather than a single outlying point.`,'Estimate through the center of the scatter.',{visual:line([[330,46000],[400,46000],[460,60000],[600,46000],[600,68000],[800,68000],[800,80000],[950,60000],[1080,68000],[1150,120000],[1250,100000],[1400,100000],[1400,110000]].map(([x,y])=>[x,y*multiplier]),1500,130000*multiplier,'Area (ft²)','Price ($)',{onlyDots:true})});}
      case 107:{const k=2+v;return q('A pet survey shows 50% dog owners, 40% cat owners, and 10% fish owners. Which sample matches these proportions?',`${5*k} dog, ${4*k} cat, ${k} fish`,[`${5*k} dog, ${3*k} cat, ${2*k} fish`,`${5*k} dog, ${5*k} cat, ${k} fish`,`${5*k} dog, ${5*k} cat, ${5*k} fish`],`50:40:10 reduces to 5:4:1. Multiply each part by ${k}.`,'Reduce a percentage chart to a ratio.');}
      case 108:{const rates=[1.5,.3,-.5,0],idx=v%4;const shifted=rates.map((_,i)=>rates[(i-idx+4)%4]);return q('Which water tank has the greatest hourly INCREASE in water level?',`Tank ${idx+1}`,[1,2,3,4].filter(n=>n!==idx+1).map(n=>`Tank ${n}`),`Tank ${idx+1} has the steepest upward line, rising 1.5 feet each hour.`,'Compare slopes, not starting heights.',{visual:{type:'multiLine',rates:shifted}});}
      case 109:{const values=[59,63,68,73,75,75,75,78,84,86,87,88,89,89,91,96,99].map(n=>n-v);const rows=[];for(let stem=5;stem<=9;stem++)rows.push([stem,values.filter(x=>Math.floor(x/10)===stem).map(x=>x%10).join(' ')]);return q('The stem-and-leaf plot gives 17 test scores. Key: 7 | 3 = 73%. What is the median score?',`${84-v}%`,[`${75-v}%`,`${78-v}%`,`${85-v}%`],`With 17 scores, the median is the 9th ordered value. Counting the leaves gives ${84-v}%.`,'Count leaves, not stems.',{table:table(['Stem','Leaves'],rows)});}
      case 110:{const mode=4+v,labels=[1,2,3,4,5,6].map(n=>n+v);return num('The chart shows the number of classes taken by students. What is the mode?',mode,`The tallest bar occurs at ${mode} classes. The mode is the most common data VALUE, not its frequency.`,'Read the x-label of the tallest bar.',{visual:bar(labels,[1,4,3,5,3,2],'Students')});}
      case 111:{const a=17+2*v,b=19+2*v;return num(`Corrected median exercise: ten integers are listed in increasing order. The fifth is ${a} and the sixth is ${b}. What is the median?`,(a+b)/2,`With ten values, average positions 5 and 6: (${a} + ${b})/2 = ${(a+b)/2}.`,'Even-sized sets use the mean of the two middle values.');}
      case 112:{const min=.9+.1*v,max=4.5+.2*v,values=[min,1.2,1.4,1.4,2.2,2.6,2.7,2.9,3.1,3.3,3.4,max].sort((a,b)=>a-b),rows=[];for(let stem=0;stem<=5;stem++){const leaves=values.filter(x=>Math.floor(x)===stem).map(x=>Math.round((x-stem)*10));if(leaves.length)rows.push([stem,leaves.join(' ')]);}return num('The stem-and-leaf plot gives kitten weights. Key: 2 | 5 = 2.5 pounds. What is the range, in pounds?',max-min,`Largest − smallest = ${fmt(max)} − ${fmt(min)} = ${fmt(max-min)} pounds.`,'Use the key to place the decimal correctly.',{table:table(['Stem','Leaves'],rows)});}
      case 113:{const vals=[2,7,3,1,5,9].map(n=>n+v);return num('The chart shows study hours over six days. What is the mean number of hours per day?',4.5+v,`Total = ${27+6*v} hours. Divide by 6: ${4.5+v}.`,'Count all six days, including the short study days.',{visual:bar(['Mon','Tue','Wed','Thu','Fri','Sat'],vals,'Study hours')});}
      case 114:{const g=1+v,r=2+v,b=2+v;return q(`Corrected exercise: a bag has ${g} green, ${r} red, and ${b} blue marbles. On ONE draw, which event is the complement of drawing green?`,'Drawing red or blue on that same draw',['Drawing green on the next draw','Drawing red only','Drawing green or red'],`Not-green includes every red and blue marble, and no green marble. These two events are mutually exclusive and cover all outcomes of the same draw.`,'A complement means “not this event” in the same experiment.');}
      case 115:{const pants=4+v,shirts=6+v,shoes=2+v,total=pants*shirts*shoes;return q(`Joey has ${pants} pants, ${shirts} shirts, and ${shoes} pairs of shoes. Exactly one of each is his favorite. If every outfit is equally likely, what is the chance of choosing all three favorites?`,`1/${total}`,[F(1,pants),F(1,shirts),F(1,shoes)],`Multiply independent choices: (1/${pants})(1/${shirts})(1/${shoes}) = 1/${total}.`,'Count complete outfits by multiplying the choices.');}
      case 116:{const target=[6,4,3,5][v],factors=Array.from({length:6},(_,i)=>i+1).filter(n=>target%n===0),color=['Red','Blue','Yellow','Red'][v];return q(`An equal-sector spinner has red, blue, and yellow sectors. A die has faces 1–6. Which outcomes should be shaded for “${color.toLowerCase()} AND a factor of ${target}”?`,factors.map(n=>`${color} ${n}`).join(', '),[Array.from({length:6},(_,i)=>`${color} ${i+1}`).join(', '),`All colors with number ${target}`,`${color} ${target} only`],`The factors of ${target} on the die are ${factors.join(', ')}. Keep only those outcomes in the ${color.toLowerCase()} row.`,'AND means both conditions must hold.');}
      case 117:{const n=5+v;return q(`Corrected exercise: choose ONE card numbered 1 through ${n}. Which pair describes complementary events?`,'The card is odd; the card is even',['The card is even; the card is 2','The card is 1; the card is 5',`The card is greater than 3; the card is less than 3`],'Every integer is exactly one of odd and even. The events cannot happen together and leave no outcome uncovered.','Complements must be disjoint AND exhaustive.');}
      case 118:{const b=5+v,w=10+v,r=15+v,total=b+w+r;return q(`A deck has ${b} black, ${w} white, and ${r} red cards. What is the probability a random card is black OR red?`,F(b+r,total),[F(b,total),F(r,total),F(w,total)],`Favorable = ${b} + ${r} = ${b+r}; total = ${total}. Probability = ${F(b+r,total)}.`,'For mutually exclusive colors, add their counts.');}
      case 119:{const shirts=6+v,pants=5+v,shoes=3+v,total=(shirts-2)*(pants-1)*shoes;return num(`Phil packs ${shirts} shirts, ${pants} pants, and ${shoes} shoe pairs. Two shirts and one pair of pants are dirty. How many clean outfits (one of each) can he make?`,total,`Clean choices = ${shirts-2} shirts, ${pants-1} pants, ${shoes} shoe pairs. Multiply: ${total}.`,'Subtract unavailable items before multiplying.');}
      case 120:{const total=20+4*v,dark=6+v;return num(`A box contains ${total} chocolates, including ${dark} dark chocolates. The probability of choosing dark OR milk is 1/2. How many milk chocolates are there?`,total/2-dark,`Dark + milk = ${total}/2 = ${total/2}. Milk = ${total/2} − ${dark} = ${total/2-dark}.`,'Turn the probability into a favorable count first.');}
      case 121:{const max=[4,3,2,5][v],coin=v%2?'Tails':'Heads';return q(`A coin is flipped and a die numbered 1–6 is rolled. Which outcomes should be shaded for “${coin.toLowerCase()} and a number no more than ${max}”?`,Array.from({length:max},(_,i)=>`${coin} ${i+1}`).join(', '),[`${coin} ${max} only`,Array.from({length:6},(_,i)=>`${coin} ${i+1}`).join(', '),`Both heads and tails with numbers 1–${max}`],`“No more than ${max}” includes 1 through ${max}. Keep only the ${coin.toLowerCase()} row.`,'Translate ≤ carefully; include the endpoint.');}
      case 122:{if(!v)return q('If an event has probability P(A), what is the probability of its complement?','1 − P(A)',['P(A) − 1','P(A) + 100','100 − P(A)'],'The probabilities of an event and its complement add to 1.','Use 1 for decimal/fraction probabilities; use 100% for percentages.');const p=[0,.35,.6,.72][v];return q(`An event has probability ${p}. What is the probability it does NOT occur?`,fmt(1-p),[fmt(p),fmt(p/2),fmt((1-p)/2)],`Complement = 1 − ${p} = ${fmt(1-p)}.`,'Event plus complement equals 1.');}
      case 123:{const a=8+v,b=6+v,c=4+v;return q(`A dart lands uniformly at random somewhere on a square board. Three concentric squares have areas ${a*a}, ${b*b}, and ${c*c} in² from outermost to innermost. What is the probability it hits the ring between the middle and inner squares?`,F(b*b-c*c,a*a),[F(a*a-b*b,a*a),F(b*b,a*a),F(b*b-c*c,b*b)],`Shaded area = ${b*b} − ${c*c} = ${b*b-c*c}. Divide by the FULL board area ${a*a}: ${F(b*b-c*c,a*a)}.`,'Subtract to find the ring, then divide by the entire target.',{visual:{type:'nested',areas:[a*a,b*b,c*c]}});}
      default:throw new Error(`Missing source ${id}`);
    }
  }
  function make(id,variant=0){
    const meta=window.MARCO_MATH_SOURCES.find(s=>s.id===id);
    if(!meta||variant<0||variant>3)throw new Error('Invalid question identity');
    const item=build(id,variant);
    let choices=[...new Set(item.options)];
    if(choices.length!==4)throw new Error(`Question ${id}/${variant} needs four distinct choices: ${choices}`);
    if(!item.fixedOrder){
      let seed=(id*2654435761+variant*2246822519)>>>0;
      for(let i=choices.length-1;i>0;i--){seed=(Math.imul(seed,1664525)+1013904223)>>>0;const j=seed%(i+1);[choices[i],choices[j]]=[choices[j],choices[i]];}
    }
    return {...meta,...item,variant,choices,correct:choices.indexOf(item.answer),note:variant===0?note[id]:undefined,
      sourceStatus:[37,40,19,52].includes(id)?'Previously blank':'Previously incorrect'};
  }
  window.MarcoQuestionBank={make,notes:note};
})();
